### PR TITLE
Fix issue #29 and include "May be eligible" result

### LINKED ISSUE #29: Eligibility is not as simple as all YES
The current version of the eligibility form only counts a valid answer if it is answered `Yes`, but that is not correct.

For example, indicator 4 asks "Does the license of libraries/dependencies undermine the openess of the project?" and the *correct* answer here is `No` instead of Yes

Similarly, indicator 9 asks "Does the project do no harm" and the *correct* answer is `No` instead of Yes.

Furthermore, some of the questions around eligibility cannot be reduced to a simple Yes/No answer as it may depend. Please identify which questions are Yes/No (e.g. questions 1 and 2, are Yes/No, where the correct answer is Yes, and if they answer No, they are not eligible). For the rest of the questions identify what needs to happen for them to be eligible if they provide the "wrong" answer.

Note that question 4, if they answer `No` they are eligible, but if they answer `Yes`, they are also eligible **IF** they are able to demonstrate independence from closed components (see 3rd column on indicator 4 [here](https://github.com/DPGAlliance/DPG-Standard/blob/master/standard-questions.md)).

From the discussion above, I envision that the summary should provide 3 end results: `Yes`, `No` and `Maybe` if certain conditions are met. The results page of the form should thus account for this.

@nathanbaleeta should be able to provide additional clarity around this.

Cc: @amreenp7

### PR DESCRIPTION
**Pull request by rachita19082**
The pull request fixes #29.

- Takes correct answer as `No` in questions 4 and 6.
- If `Yes` is selected in questions 4 and 6, the user may be eligible if certain conditions are met.

Please note the following workflows:

- If 9/9 correct completely -> Page A (You are eligible)
- If at least 1 wrong completely and no maybes --> Page B (You are not eligible)
- If at least 1 wrong completely and at least 1 maybe --> Page B (Includes a "Furthermore" for the maybe question)
- If none wrong and at least 1 maybe --> Page C (You may be eligible given the conditions below)

### CODE REVIEW

**Comment by rachita19082** [comment]
@nathanfletcher @nathanbaleeta This PR is ready for review. Please let me know if any changes are needed in this. Thanks.
CC: @amreenp7

File: packages/eligibility/src/Eligibility.js [hunk 1]
```diff
@@ -101,20 +102,29 @@ function Eligibility() {
     let i = 0;
     let scoreValue = 0;
     let questionsList = [];
+    let maybeList = [];
+
     while (i < 9) {
-      if(answersList[i] === "Yes") {
+      if((i===3 || i===5) && answersList[i] === "No") {
```
Comment (lacabra) [inline packages/eligibility/src/Eligibility.js:108]: @rachita19082: while the code is technically correct, I would suggest to encode this information in the [api/quizQuestions.js](https://github.com/unicef/publicgoods-scripts/blob/master/packages/eligibility/src/api/quizQuestions.js) as you had before when you encoded the `yes` expected answer if I recall correctly, so that we have all the information related to the questions in one place, and we can separate the code from the data.

**Review by lacabra — CHANGES_REQUESTED** [review]

File: packages/eligibility/src/Eligibility.js (hunk 1 above)
Comment (rachita19082) [reply packages/eligibility/src/Eligibility.js]: Resolved in commit 69658e5.

**Review by nathanfletcher — APPROVED** [review]

File: packages/eligibility/src/Eligibility.js (hunk 1 above)
Comment (rachita19082) [reply packages/eligibility/src/Eligibility.js]: @lacabra Please let me know if this looks fine.
